# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2021-01-28 00:59
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0002_todo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Requisicao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('backlog', 'backlog'), ('pending', 'pending'), ('ongoing', 'ongoing'), ('done', 'done'), ('delivered', 'delivered')], max_length=20, null=True)),
                ('archived', models.BooleanField(default=False)),
                ('analysis', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('priority', models.IntegerField(blank=True, choices=[(0, 'prioridade 0'), (1, 'prioridade 1'), (2, 'prioridade 2'), (3, 'prioridade 3')])),
                ('category', models.CharField(blank=True, choices=[('compra', 'compra'), ('manutenção', 'manutenção'), ('obra', 'obra')], max_length=20)),
                ('link', models.URLField(blank=True, max_length=400)),
                ('description', models.TextField(blank=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Todo',
        ),
    ]
