# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2021-01-28 01:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20210128_0059'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Requisicao',
            new_name='Requisition',
        ),
    ]
