# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2021-01-28 14:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_requisition_is_trash'),
    ]

    operations = [
        migrations.AddField(
            model_name='requisition',
            name='team',
            field=models.CharField(blank=True, choices=[('operações', 'operações'), ('tecnologia', 'tecnologia'), ('marketing', 'marketing'), ('people', 'people'), ('finance', 'finance'), ('suporte', 'suporte')], max_length=20),
        ),
    ]
