# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2021-01-28 20:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_requisition_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='requisition',
            name='index',
            field=models.IntegerField(null=True),
        ),
    ]
