# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2021-01-28 23:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_requisition_index'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requisition',
            name='index',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
